project:
  type: website
  output-dir: docs
  pre-render: 
    - quarto-scripts/create-teaching-yml.r

website:
  title: "PSICOSTAT"
  favicon: assets/faviconpsicostat.png
  navbar:
    logo: assets/simplelogopsicostat.png
    logo-href: https://psicostat.dpss.psy.unipd.it/

format:
   html:
      css: custom.css

execute: 
  freeze: true