project:
  type: website
  output-dir: docs

website:
  title: "Psicostat teachings and workshops"
  favicon: assets/faviconpsicostat.png
  navbar:
    logo: assets/psicostatLogo.png

format:
   html:
      css: custom.css

execute: 
  freeze: true