project:
  type: website
  output-dir: docs

website:
  title: "Psicostat teachings and workshops"
  navbar:
    left:
      - href: index.qmd
        text: home
format:
   html:
      css: custom.css

execute: 
  freeze: true