project:
  type: website
  output-dir: docs
  pre-render: 
    - quarto-scripts/create-teaching-yml.r

website:
  title: "Psicostat teachings and workshops"
  favicon: assets/faviconpsicostat.png
  navbar:
    logo: assets/simplelogopsicostat.png

format:
   html:
      css: custom.css

execute: 
  freeze: true